//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.04 at 03:52:06 PM KST 
//


package com.systems88.validate.bti.bean;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="status_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="member_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="member_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="odds_style" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="datetime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Sport">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Branch" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MaxBet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MaxBetPerMatch" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="MinBet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="MaxBet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="MinBet" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "statusCode",
    "currency",
    "memberId",
    "memberName",
    "language",
    "oddsStyle",
    "datetime",
    "sport"
})
@XmlRootElement(name = "AuthSessionTokenResponse")
public class AuthSessionTokenResponse {

    @XmlElement(name = "status_code", required = true)
    protected String statusCode;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(name = "member_id", required = true)
    protected String memberId;
    @XmlElement(name = "member_name", required = true)
    protected String memberName;
    @XmlElement(required = true)
    protected String language;
    @XmlElement(name = "odds_style", required = true)
    protected String oddsStyle;
    @XmlElement(required = true)
    protected String datetime;
    @XmlElement(name = "Sport", required = true)
    protected AuthSessionTokenResponse.Sport sport;

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the memberId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberId() {
        return memberId;
    }

    /**
     * Sets the value of the memberId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberId(String value) {
        this.memberId = value;
    }

    /**
     * Gets the value of the memberName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * Sets the value of the memberName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMemberName(String value) {
        this.memberName = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the oddsStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOddsStyle() {
        return oddsStyle;
    }

    /**
     * Sets the value of the oddsStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOddsStyle(String value) {
        this.oddsStyle = value;
    }

    /**
     * Gets the value of the datetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatetime() {
        return datetime;
    }

    /**
     * Sets the value of the datetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatetime(String value) {
        this.datetime = value;
    }

    /**
     * Gets the value of the sport property.
     * 
     * @return
     *     possible object is
     *     {@link AuthSessionTokenResponse.Sport }
     *     
     */
    public AuthSessionTokenResponse.Sport getSport() {
        return sport;
    }

    /**
     * Sets the value of the sport property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthSessionTokenResponse.Sport }
     *     
     */
    public void setSport(AuthSessionTokenResponse.Sport value) {
        this.sport = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Branch" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="MaxBet" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="MaxBetPerMatch" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="MinBet" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="MaxBet" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="MinBet" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "branch"
    })
    public static class Sport {

        @XmlElement(name = "Branch")
        protected List<AuthSessionTokenResponse.Sport.Branch> branch;
        @XmlAttribute(name = "MaxBet")
        protected String maxBet;
        @XmlAttribute(name = "MinBet")
        protected String minBet;

        /**
         * Gets the value of the branch property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the branch property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getBranch().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuthSessionTokenResponse.Sport.Branch }
         * 
         * 
         */
        public List<AuthSessionTokenResponse.Sport.Branch> getBranch() {
            if (branch == null) {
                branch = new ArrayList<AuthSessionTokenResponse.Sport.Branch>();
            }
            return this.branch;
        }

        /**
         * Gets the value of the maxBet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaxBet() {
            return maxBet;
        }

        /**
         * Sets the value of the maxBet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaxBet(String value) {
            this.maxBet = value;
        }

        /**
         * Gets the value of the minBet property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMinBet() {
            return minBet;
        }

        /**
         * Sets the value of the minBet property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMinBet(String value) {
            this.minBet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="MaxBet" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="MaxBetPerMatch" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="MinBet" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Branch {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "ID")
            protected String id;
            @XmlAttribute(name = "MaxBet")
            protected String maxBet;
            @XmlAttribute(name = "MaxBetPerMatch")
            protected String maxBetPerMatch;
            @XmlAttribute(name = "MinBet")
            protected String minBet;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the maxBet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxBet() {
                return maxBet;
            }

            /**
             * Sets the value of the maxBet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxBet(String value) {
                this.maxBet = value;
            }

            /**
             * Gets the value of the maxBetPerMatch property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMaxBetPerMatch() {
                return maxBetPerMatch;
            }

            /**
             * Sets the value of the maxBetPerMatch property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMaxBetPerMatch(String value) {
                this.maxBetPerMatch = value;
            }

            /**
             * Gets the value of the minBet property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMinBet() {
                return minBet;
            }

            /**
             * Sets the value of the minBet property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMinBet(String value) {
                this.minBet = value;
            }

        }

    }

}
