//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.04 at 03:52:06 PM KST 
//


package com.systems88.validate.bti.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.systems88.validate.bti.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.systems88.validate.bti.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AuthSessionTokenResponse }
     * 
     */
    public AuthSessionTokenResponse createAuthSessionTokenResponse() {
        return new AuthSessionTokenResponse();
    }

    /**
     * Create an instance of {@link AuthSessionTokenResponse.Sport }
     * 
     */
    public AuthSessionTokenResponse.Sport createAuthSessionTokenResponseSport() {
        return new AuthSessionTokenResponse.Sport();
    }

    /**
     * Create an instance of {@link AuthSessionTokenRequest }
     * 
     */
    public AuthSessionTokenRequest createAuthSessionTokenRequest() {
        return new AuthSessionTokenRequest();
    }

    /**
     * Create an instance of {@link AuthSessionTokenResponse.Sport.Branch }
     * 
     */
    public AuthSessionTokenResponse.Sport.Branch createAuthSessionTokenResponseSportBranch() {
        return new AuthSessionTokenResponse.Sport.Branch();
    }

}
